### ISSUE TITLE
Method (Make decision about reuse or argue)

### ISSUE THREAD

**Issue by cpfaff** [cpfaff/ease#20]
We do:

``` XML
<xs:element name="method" minOccurs="1" maxOccurs="1">
    <xs:complexType>
    <xs:sequence>
        <xs:element name="methodologicalCoverage" minOccurs="1" maxOccurs="1">
        <xs:complexType>
            <xs:sequence>
            <xs:element name="methodApproach" type="methodApproachType" minOccurs="1" maxOccurs="1">
            </xs:element>
            <xs:element name="methodRange" minOccurs="1" maxOccurs="1">
                <xs:complexType>
                <xs:sequence>
                    <xs:element name="methodItem" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                        <xs:element name="methodName" type="xs:string" minOccurs="0" maxOccurs="1">
                        </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                    </xs:element>
                </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="controlFactorRange" minOccurs="1" maxOccurs="1">
                <xs:complexType>
                <xs:sequence>
                    <xs:element name="controlFactorItem" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                        <xs:element name="controlFactorName" type="factorNameType" minOccurs = "1" maxOccurs = "1">
                        </xs:element>
                        <xs:element name="controlFactorModus" type="factorModus" minOccurs = "1" maxOccurs = "1">
                        </xs:element>
                        <xs:element name="controlFactorDependency" type="controlFactorDependencyType" minOccurs="1" maxOccurs="1">
                        </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                    </xs:element>
                </xs:sequence>
                </xs:complexType>
            </xs:element>
            </xs:sequence>
        </xs:complexType>
        </xs:element>
    </xs:sequence>
    </xs:complexType>
</xs:element>
```

ABCD does:

``` XML
<xs:element type="StringL" name="Method" minOccurs="0">
    <xs:annotation>
        <xs:documentation>The method (including technical means) used to make the collection or observation.</xs:documentation>
    </xs:annotation>
</xs:element>

<xs:element type="String" name="CoordinateMethod" minOccurs="0">
    <xs:annotation>
        <xs:documentation>Coordinates measuring system e.g. GPS, field map reference, inferred map reference</xs:documentation>
    </xs:annotation>
</xs:element>

<xs:element type="String" name="CoordinateErrorMethod" minOccurs="0"/>
```

DwC does nothing:

EML does:

``` XML
  <xs:complexType name="MethodsType">
    <xs:sequence maxOccurs="unbounded">
      <xs:element name="methodStep" maxOccurs="unbounded">
        <xs:complexType>
          <xs:complexContent>
            <xs:extension base="ProcedureStepType">
              <xs:sequence>
                <xs:element name="dataSource" type="ds:DatasetType" minOccurs="0" maxOccurs="unbounded">
                </xs:element>
              </xs:sequence>
            </xs:extension>
          </xs:complexContent>
        </xs:complexType>
      </xs:element>
      <xs:element name="sampling" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="studyExtent">
              <xs:complexType>
                <xs:choice maxOccurs="unbounded">
                  <xs:element name="coverage" type="cov:Coverage">
                  </xs:element>
                  <xs:element name="description" type="txt:TextType">
                  </xs:element>
                </xs:choice>
              </xs:complexType>
            </xs:element>
            <xs:element name="samplingDescription" type="txt:TextType">
            </xs:element>
            <xs:element name="spatialSamplingUnits" minOccurs="0">
              <xs:complexType>
                <xs:choice maxOccurs="unbounded">
                  <xs:element name="referencedEntityId">
                  </xs:element>
                  <xs:element name="coverage" type="cov:GeographicCoverage">
                  </xs:element>
                </xs:choice>
              </xs:complexType>
            </xs:element>
            <xs:element name="citation" type="cit:CitationType" minOccurs="0" maxOccurs="unbounded">
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="qualityControl" type="ProcedureStepType" minOccurs="0" maxOccurs="unbounded">
      </xs:element>
    </xs:sequence>
  </xs:complexType>

```

**Comment by cpfaff** [comment]
While ABCD is asking for methods in multiple places of the schema DwC does not mention methods at all. Our general approach field is the one closest to the general method in ABCD. EML has the most sophisticated module in regards of methods. The eml-methods module describes the methods followed in the creation of the dataset, including description of field, laboratory and processing steps, sampling methods and units, quality control procedures.

**Comment by cpfaff** [comment]
Altough tempting to adapt EML is very detailed with capturing the methods that have been followed as well as the details that revolve around it. Actually I think we should not dive into that detail. I would argue to keep what we have in CAS as we already offer a way to specify methods by name additionally to the general approach of the project.

**Comment by cpfaff** [comment]
Thinking about how good this method name will work for tagging and search. Asking for a method name only might only work well established methods that everybody knows and which are always conducted with people following the same protocol. This will hardly happen very often. So maybe as it is done currently it is not very helpful.

**Comment by EichenbergBEF** [comment]
I am worrying about the following (and this is a general issue): How do 
we assure that datasets are not only annotated by CAS, without any 
detailed metainformation e.g. given in EML. I mean the following: If you 
upload a dataset using CAS, you may well be able to annotate a method 
(like cation exchange capacity). However, detailed information on which 
liquid phase was used or which electrode will not be szuitable (and 
necessary) to provide with CAS. However, these details should be given 
if the dataset has been described according to meatadata-schemes like 
EML. If this infromation is not given within the dataset itself, nobody 
will be able to find out. So, maybe we should think about some "safety 
hook" like that Datasets without any additional metadata cannot be 
annotated with CAS.
People tend to be lazy... always.
Do you understand what I mean?

Am 16.12.2015 um 10:51 schrieb Claas-Thido Pfaff:

> Asking for a method name only however only works for well established 
> methods everybody knows and that is always conducted following the 
> same protocol. Otherwise the tagging with it is not helpful.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/cpfaff/cas/issues/20#issuecomment-165051151.

## 

Dr. rer. nat. David Eichenberg
BEF-China research consortium
Data manager (BEF China Dataportal)
Tel: 0049-341-9738587
Department of Systematic Botany and Functional Biodiversity
University of Leipzig
Room 120
Johannisalles 21
04103 Leipzig GERMANY

**Comment by cpfaff** [comment]
I see the problem and I would not argue that the detail information is not important. It is by far the most important if you want to decide in detail if a method is compatible to the one from your data and if you can use another set of data for a synthesis or not. With CAS we do not account for that level of detail. Maybe we have to remove named methods from our schema and only provide the predefined set of general approaches that we have and stop with that. I am just thinking with our control factors it is quite similar. As a simple example we can specify that somebody measured DBH however you cannot see how it has been measured nor is there an explanation.
