### ISSUE TITLE
Think about usage of elevation

### ISSUE THREAD

**Issue by cpfaff** [cpfaff/ease#28]
See: http://english.stackexchange.com/questions/16610/which-to-use-altitude-or-elevation-in-regards-to-height-above-sea-level

**Comment by cpfaff** [comment]
I think it is better to use elevation over altitude due to the post above.

**Comment by EichenbergBEF** [comment]
I totally agree.
Funny discussions with quite elaborate answers.

Zitat von Claas-Thido Pfaff notifications@github.com:
