### ISSUE TITLE
Find a better name than cas

### ISSUE THREAD

**Issue by cpfaff** [cpfaff/ease#45]
- I like feat (Fast Ecological Annotation Tool) in German feat means Heldentat.

@EichenbergBEF  what do you think about that? Other suggestions are welcome.

**Comment by EichenbergBEF** [comment]
Being somewhat heroic, what?? ;-)

Am 07.01.2016 um 15:24 schrieb Claas-Thido Pfaff:

> - I like feat (Fast Ecological Annotation Tool) in German feat means
>   Heldentat.
> 
> @EichenbergBEF https://github.com/EichenbergBEF what do you think 
> about that? Other suggestions are welcome.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/cpfaff/cas/issues/45.

## 

Dr. rer. nat. David Eichenberg
BEF-China research consortium
Data manager (BEF China Dataportal)
Tel: 0049-341-9738587
Department of Systematic Botany and Functional Biodiversity
University of Leipzig
Room 120
Johannisalles 21
04103 Leipzig GERMANY

**Comment by EichenbergBEF** [comment]
How about brain (Biological Research Annotation Incentive Network)?

Am 07.01.2016 um 15:24 schrieb Claas-Thido Pfaff:

> - I like feat (Fast Ecological Annotation Tool) in German feat means
>   Heldentat.
> 
> @EichenbergBEF https://github.com/EichenbergBEF what do you think 
> about that? Other suggestions are welcome.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/cpfaff/cas/issues/45.

## 

Dr. rer. nat. David Eichenberg
BEF-China research consortium
Data manager (BEF China Dataportal)
Tel: 0049-341-9738587
Department of Systematic Botany and Functional Biodiversity
University of Leipzig
Room 120
Johannisalles 21
04103 Leipzig GERMANY

**Comment by EichenbergBEF** [comment]
CAFE: Comprehensive Annotation For Ecology

Am 07.01.2016 um 15:24 schrieb Claas-Thido Pfaff:

> - I like feat (Fast Ecological Annotation Tool) in German feat means
>   Heldentat.
> 
> @EichenbergBEF https://github.com/EichenbergBEF what do you think 
> about that? Other suggestions are welcome.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/cpfaff/cas/issues/45.

## 

Dr. rer. nat. David Eichenberg
BEF-China research consortium
Data manager (BEF China Dataportal)
Tel: 0049-341-9738587
Department of Systematic Botany and Functional Biodiversity
University of Leipzig
Room 120
Johannisalles 21
04103 Leipzig GERMANY

**Comment by cpfaff** [comment]
I like 
- FEAT
- CAFE

**Comment by EichenbergBEF** [comment]
I like feat best :-)

Am 18.01.2016 um 12:25 schrieb Claas-Thido Pfaff:

> I like
> - FEAT
> - CAFE
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/cpfaff/cas/issues/45#issuecomment-172502645.

## 

Dr. rer. nat. David Eichenberg
BEF-China research consortium
Data manager (BEF China Dataportal)
Tel: 0049-341-9738587
Department of Systematic Botany and Functional Biodiversity
University of Leipzig
Room 120
Johannisalles 21
04103 Leipzig GERMANY

**Comment by cpfaff** [comment]
We just take feat.

**Comment by cpfaff** [comment]
But it is not only a tool. It is rather a framework that consist of a tool and a vocabulary. Thus the "t" in feat does not fit.

**Comment by EichenbergBEF** [comment]
Well... if this is a conceptual problem, then maybe 'cafe' would also be 
an option. I like the general concept of this naming. However, I think 
this is not an urgent matter after all and we could spend some more time 
on further alternatives.

Am 18.01.2016 um 12:37 schrieb Claas-Thido Pfaff:

> But it is not only a tool. It is rather a framework that consist of a 
> tool and a vocabulary. Thus the "t" in feat does not fit.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/cpfaff/feat/issues/45#issuecomment-172504506.

## 

Dr. rer. nat. David Eichenberg
BEF-China research consortium
Data manager (BEF China Dataportal)
Tel: 0049-341-9738587
Department of Systematic Botany and Functional Biodiversity
University of Leipzig
Room 120
Johannisalles 21
04103 Leipzig GERMANY

**Comment by EichenbergBEF** [comment]
btw: then it would still have the 'C' with all its intrinsic and 
insider-knowledge based implications... which I feel would be dereved in 
the end :-)

Am 18.01.2016 um 12:37 schrieb Claas-Thido Pfaff:

> But it is not only a tool. It is rather a framework that consist of a 
> tool and a vocabulary. Thus the "t" in feat does not fit.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/cpfaff/feat/issues/45#issuecomment-172504506.

## 

Dr. rer. nat. David Eichenberg
BEF-China research consortium
Data manager (BEF China Dataportal)
Tel: 0049-341-9738587
Department of Systematic Botany and Functional Biodiversity
University of Leipzig
Room 120
Johannisalles 21
04103 Leipzig GERMANY

**Comment by cpfaff** [comment]
Sure. May take some more time.

**Comment by cpfaff** [comment]
Name it cafe for now.
