### ISSUE TITLE
Move aquatic physiognomy items to zones in spheres

### ISSUE THREAD

**Issue by cpfaff** [cpfaff/ease#50]
This is necessary as many items rather represent zones or layers. Introduce instead some elements for the aquatic physiognomy. They are coming from:  Alberta conservation information management system ecological community tracking [list](http://www.albertaparks.ca/media/3259838/tracked_watched_list_ecological_communities_full_report.pdf)

**Comment by EichenbergBEF** [comment]
I checked these classes and think the following: It is a somewhat 
intuitive classificiation, although I think the scheme misses some 
important points:
concerning the flowers it does not allow to classify 
flowers/inflorescents which are submergen (like e.g in some Elodea species).
Moreover it only allows to classify "rooted or attached aquatic plants". 
How to deal with datasets concerning floating vegetation? I'll try to go 
into some research ibn this respect as soon as I find time for this.

Am 25.01.2016 um 11:33 schrieb Claas-Thido Pfaff:

> This is necessary as many items rather represent zones or layers. 
> Introduce instead some elements for the aquatic physiognomy. They are 
> coming from: Alberta conservation information management system 
> ecological community tracking list 
> http://www.albertaparks.ca/media/3259838/tracked_watched_list_ecological_communities_full_report.pdf
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/cpfaff/cafe/issues/50.

## 

Dr. rer. nat. David Eichenberg
BEF-China research consortium
Data manager (BEF China Dataportal)
Tel: 0049-341-9738587
Department of Systematic Botany and Functional Biodiversity
University of Leipzig
Room 120
Johannisalles 21
04103 Leipzig GERMANY

**Comment by cpfaff** [comment]
Well great. I reopened the issue.

**Comment by cpfaff** [comment]
Well would it be sufficient just to add exactly one another category that captures the floating non attached non rooted stuff.

**Comment by cpfaff** [comment]
Maybe just name it `Non Attached`
