### ISSUE TITLE
Add processes to the ontology

### ISSUE THREAD

**Issue by cpfaff** [cpfaff/ease#79]
Currently lacking processses in the ontology.

**Comment by EichenbergBEF** [comment]
Ich weiß nich ob das vom coding her wichtig ist, aber:
Line 1810: "Process Name"; sollte das nicht ohne SPACE sein, also 
"ProcessName"?
Selbiges bei : 1924, 1929, 1934 und 1971.

Außerdem: 1871-1879: double entry von "Assimilation".

Am 02.02.2016 um 11:13 schrieb Claas-Thido Pfaff:

> Currently lacking processses in the ontology.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/cpfaff/cafe/issues/79.

## 

Dr. rer. nat. David Eichenberg
BEF-China research consortium
Data manager (BEF China Dataportal)
Tel: 0049-341-9738587
Department of Systematic Botany and Functional Biodiversity
University of Leipzig
Room 120
Johannisalles 21
04103 Leipzig GERMANY

**Comment by cpfaff** [comment]
You see the owl file here:

It contains class definitions looking like that: 

```
<Class rdf:about="http://www.semanticweb.org/ctpfaff/ontologies/2016/1/cafe#ProcessName">
+        <rdfs:subClassOf rdf:resource="http://www.semanticweb.org/ctpfaff/ontologies/2016/1/cafe#ProcessAspect"/>
+        <rdfs:label xml:lang="en">Process Name</rdfs:label>
+    </Class>
```

It is good practice to have in the uri after # the class name without spaces. Then we add a label which is the human readable format that represents what you would expect.
