### ISSUE TITLE
Check out how to connect to other ontologies best

### ISSUE THREAD

**Issue by cpfaff** [cpfaff/ease#88]
There are many ways to connect. @naouelkaram will check out which is the best one to use to link.

**Comment by naouelkaram** [comment]
In my opinion, the best solution would be to use the concept directly in the ontology by specifying the corresponding URI in the original ontology. As an example, the concept "Chemical Entity" from CHEBI (http://purl.obolibrary.org/obo/CHEBI_24431) could be directly connected either as a subclass of "Chemical Aspect" or as a replacement of that one if both are conceptually the same concept.

**Comment by naouelkaram** [comment]
Connections with different kind of ontologies need to be established (CHEBI, PATO, ENVO, etc.). The choice of which ontologies to connect to should be discussed with the involved partners
